apiVersion: v1
kind: Service
metadata:
  name: java-app-svc
spec:
  # type: ClusterIP
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
