apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    team: team1
    project: project1
spec:
  containers:
  - name: example-container
    image: example-image
  nodeSelector:
    team: team1
